// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heuxovfowuvcejxuntxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldXhvdmZvd3V2Y2VqeHVudHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzk4ODMsImV4cCI6MjA2MjU1NTg4M30.IOQKSoMnnGMudrE7i5dEKKEDfWhRYOsm_rF86Smk8VU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);